dist: trusty
sudo: false
language: python
python:
    - "2.7"
    - "pypy-5.3.1"
    - "3.5"
rvm:
    - 2.2
before_script:
    - gem install awesome_bot
install:
    - pip install -U -r requirements.txt
script:
    - pytest -vv --cov=mould --cov-report=term-missing --cov-report=html
    - flake8 setup.py mould tests
    - awesome_bot README.md --allow-dupe --allow-redirect
after_success:
    - codecov
