sudo: false
language: python
python:
    - "3.5"
    - "3.6"
install:
    - pip install -U -r requirements.txt
script:
    - pytest -vv --cov=mould --cov-report=term-missing --cov-report=html
    - flake8 setup.py mould tests
after_success:
    - codecov
