language: python
python:
    - "2.6"
    - "2.7"
    - "pypy"
install:
    - pip install -r requirements.txt
script:
    - nosetests --with-coverage --cover-package=mould
    - flake8 setup.py mould tests
after_success:
  - coveralls