language: python
python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.5"
install:
    - pip install -r requirements.txt
script:
    - pytest --cov=mould --cov-report=term --cov-report=html
    - flake8 setup.py mould tests
after_success:
    - codecov
